=== calinburloiu/microtonalist/json-schemas/v1/composition.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Composition",
    "description": "File format that defines a collection of tunings to be used in a musical composition. The player is expected to switch between the tuning while playing the composition.",
    "type": "object",
    "properties": {
        "metadata": { "$ref": "compositionMetadata.schema.json" },
        "intonationStandard": { "$ref": "intonationStandard.schema.json" },
        "tuningReference": { "$ref": "tuningReference.schema.json" },
        "baseUri": {
            "type": "string",
            "title": "Base URI",
            "description": "Custom base URI to be used for all internal URIs in this file.",
            "format": "uri-reference"
        },
        "definitions": {},
        "tunings": {
            "type": "array",
            "title": "Tunings",
            "description": "An array of tuning specifications, where each one allows a scale to be mapped to a keyboard tuning.",
            "items": { "$ref": "tuningMapper.schema.json" }
        },
        "defaultFill": {
            "allOf": [
                {
                    "title": "Default Fill",
                    "description": "Fallback tuning to be used for unused keyboard keys.\nIf this fallback itself, does not define tuning values for some unused keys, then, the standard 12-EDO tuning values are used for those keys (values with a deviation of 0 cents). If the defaultFill is not provided, unused keys will use the standard 12-EDO tuning."
                },
                { "$ref": "tuningSpec.schema.json" }
            ]
        },
        "tuningReducer": {},
        "settings": {
            "type": "object",
            "properties": {
                "tuningMapper": {
                    "type": "object",
                    "properties": {
                        "manual": { "$ref": "tuningMapper.schema.json#/$defs/manualSettings" },
                        "auto": { "$ref": "tuningMapper.schema.json#/$defs/autoSettings" }
                    }
                }
            }
        }
    },
    "required": ["tuningReference", "tunings"]
}

=== calinburloiu/microtonalist/json-schemas/v1/samples/composition.json
{
    "$schema": "../composition.schema.json",
    "tuningReference": {
        "type": "concertPitch",
        "concertPitchToBaseInterval": "3/2",
        "baseMidiNote": 76,
        "concertPitchFrequency": 432
    },
    "definitions": {
        "scales": {
            "ussak": "ussak.jscl",
            "rast": ["9/8", "fgd"],
            "&^&": null
        }
    },
    "tunings": [

    ],
    "defaultFill": {
        "transposition": "3/2",
        "transpositionIntervalNumber": 5,
        "scale": "rast.jscl",
        "tuningMapper": {
            "type": "manual",
            "keyboardMapping": [0, null, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
        }
    },
    "baseUri": "/path/to/file",
    "settings": {
        "tuningMapper": {
            "manual": {
                "keyboardMapping": [0, null, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
            },
            "auto": {
                "shouldMapQuarterTonesLow": true
            }
        }
    }
}
