=== calinburloiu/microtonalist/json-schemas/scale.schema.json
{
    "$comment": "TODO Add $id",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "Microtonalist App scale format",
    "type": "object",
    "properties": {
        "author": {
            "type": "string",
            "description": "The person or organization who created the scale"
        },
        "name": {
            "type": "string",
            "description": "The name of the scale"
        },
        "intonationStandard": {
            "$ref": "intonationStandard.schema.json",
            "default": "cents",
            "description": "Intonation Standard, which describes how microtonal intervals are expressed"
        },
        "pitches": {
            "type": "array",
            "items": { "$ref": "pitch.schema.json" },
            "minItems": 1,
            "description": "An array of scale pitches starting from the second scale degree (the tonic is implied to be a unison)"
        }
    },
    "required": ["name", "pitches"],
    "$defs": {
        "scalePitch": {

        }
    }
}

=== calinburloiu/microtonalist/json-schemas/samples/scale.json
{
    "$schema": "../scale.schema.json",

    "author": "Calin",
    "name": "Rast",
    "intonationStandard": {
        "type": "edo",
        "divisionCount": 72
    },
    "pitches": [
        69,
        383.33,
        "5/4",
        {
            "name": "segah",
            "interval": "5/4"
        }
    ]
}
